# Generated by Django 2.2.2 on 2019-06-12 20:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('asset_name', models.CharField(max_length=30)),
                ('asset_class', models.CharField(max_length=30)),
                ('asset_price', models.DecimalField(decimal_places=2, max_digits=9)),
                ('sold_assets', models.BooleanField(default=False)),
            ],
        ),
    ]
