# Generated by Django 2.2.2 on 2019-06-13 17:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='asset_quantity',
            field=models.CharField(default='', max_length=30),
            preserve_default=False,
        ),
    ]
