# Generated by Django 2.2.2 on 2019-06-18 18:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='value_sum',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
