# Generated by Django 2.2.2 on 2019-06-14 13:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('finance_app', '0002_item_asset_quantity'),
    ]

    operations = [
        migrations.RenameField(
            model_name='item',
            old_name='asset_price',
            new_name='price',
        ),
        migrations.RenameField(
            model_name='item',
            old_name='asset_quantity',
            new_name='quantity',
        ),
    ]
