# Generated by Django 2.2.2 on 2019-06-18 20:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance_app', '0003_auto_20190618_2026'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='port_return',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
