# Generated by Django 2.2.2 on 2019-06-17 15:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance_app', '0005_auto_20190617_1510'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='sold_assets',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
    ]
