# Generated by Django 2.2.2 on 2019-06-17 15:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance_app', '0007_auto_20190617_1519'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='sold_assets',
            field=models.BooleanField(default=False),
        ),
    ]
